"""Pydantic data models for the lead generation pipeline."""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class LeadStatus(str, Enum):
    PENDING = "pending"
    ENRICHED = "enriched"
    SCORED = "scored"
    OUTREACHED = "outreached"
    DISQUALIFIED = "disqualified"


class CompanySize(str, Enum):
    MICRO = "1-10"
    SMALL = "11-50"
    MEDIUM = "51-200"
    LARGE = "201-500"
    ENTERPRISE = "500+"


class Lead(BaseModel):
    """Represents a single B2B lead throughout the pipeline lifecycle."""

    # --- Identity ---
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    # --- Company ---
    company_name: str
    industry: str
    company_size: CompanySize
    annual_revenue: Optional[str] = None
    website: Optional[str] = None
    location_city: str
    location_country: str

    # --- Contact ---
    contact_name: str
    contact_title: str
    contact_email: str
    contact_linkedin: Optional[str] = None

    # --- Lead metadata ---
    lead_source: str
    product_interest: str
    pain_points: str

    # --- Enriched by enrichment.py ---
    tech_stack: Optional[str] = None
    company_description: Optional[str] = None

    # --- Scored by scoring.py ---
    score: Optional[int] = Field(default=None, ge=1, le=10)
    score_reasoning: Optional[str] = None

    # --- Generated by outreach.py ---
    outreach_subject: Optional[str] = None
    outreach_message: Optional[str] = None

    # --- Tracking ---
    status: LeadStatus = LeadStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.utcnow)
    processed_at: Optional[datetime] = None


class ScoringResult(BaseModel):
    """Output of the AI scoring step for a single lead."""

    lead_id: str
    score: int = Field(ge=1, le=10)
    reasoning: str
    qualification_tier: str  # "hot" | "warm" | "cold"


class OutreachResult(BaseModel):
    """Output of the AI outreach generation step for a single lead."""

    lead_id: str
    subject: str
    message: str
    personalization_hooks: list[str]


class PipelineResult(BaseModel):
    """Summary report produced at the end of a full pipeline run."""

    total_leads: int
    enriched: int
    scored: int
    outreached: int
    disqualified: int
    hot_leads: int
    warm_leads: int
    cold_leads: int
    output_file: str
    processed_at: datetime = Field(default_factory=datetime.utcnow)
